- type: replace
  path: /stemcells/alias=default/name
  value: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

- type: replace
  path: /instance_groups/name=pdns_private/instances
  value: 2

- type: replace
  path: /instance_groups/name=pdns_public/instances
  value: 4

- type: replace
  path: /instance_groups/name=pdns_private/vm_type
  value: pdns

- type: replace
  path: /instance_groups/name=pdns_public/vm_type
  value: pdns

- type: replace
  path: /instance_groups/name=pdns_private/azs
  value: [z1]

- type: replace
  path: /instance_groups/name=pdns_private/networks
  value:
  - name: dns-private
    static_ips: ((terraform_outputs.production_dns_private_ips))

- type: replace
  path: /instance_groups/name=pdns_public/networks
  value:
  - name: dns-public
    default: [dns, gateway]
  - name: dns-public-vip
    static_ips: ((terraform_outputs.production_dns_public_ips))
