---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

- name: s3-iam
  type: docker-image
  source:
    repository: 18fgsa/s3-resource

resources:
- name: pdns-config
  type: git
  source:
    uri: ((pdns-config-uri))
    branch: ((pdns-config-branch))

- name: pipeline-tasks
  type: git
  source:
    uri: ((pipeline-tasks-uri))
    branch: ((pipeline-tasks-branch))

- name: pdns-release
  type: s3-iam
  source:
    bucket: ((s3-bosh-releases-bucket))
    private: true
    regexp: pdns-(.*).tgz
    region_name: ((aws-region))

- name: stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

- name: terraform-yaml
  type: s3-iam
  source:
    bucket: ((tf-state-bucket))
    versioned_file: ((tf-state-file))
    region_name: ((aws-region))

- name: common-staging
  type: s3-iam
  source:
    bucket: ((private-staging-bucket))
    versioned_file: staging-pdns.yml
    region_name: ((aws-region))

- name: common-production
  type: s3-iam
  source:
    bucket: ((private-production-bucket))
    versioned_file: production-pdns.yml
    region_name: ((aws-region))

- name: pdns-deployment-staging
  type: bosh-deployment
  source:
    target: ((staging-bosh-target))
    client: ((staging-bosh-client))
    client_secret: ((staging-bosh-client-secret))
    ca_cert: ((bosh-ca-cert))
    deployment: pdns-staging

- name: pdns-deployment-production
  type: bosh-deployment
  source:
    target: ((production-bosh-target))
    client: ((production-bosh-client))
    client_secret: ((production-bosh-client-secret))
    ca_cert: ((bosh-ca-cert))
    deployment: pdns-production

- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))

- name: tests-timer
  type: time
  source:
    interval: 10m

jobs:
- name: deploy-pdns-staging
  plan:
  - aggregate:
    - get: pdns-config
      trigger: true
    - get: pdns-release
      trigger: true
    - get: stemcell
      trigger: true
    - get: terraform-yaml
    - get: common-staging
      trigger: true
  - task: terraform-secrets
    file: pdns-config/ci/terraform-secrets.yml
    params:
      ENVIRONMENT: staging
  - put: pdns-deployment-staging
    params:
      manifest: pdns-config/deployment.yml
      stemcells:
      - stemcell/*.tgz
      releases:
      - pdns-release/*.tgz
      ops_files:
      - pdns-config/opsfiles/staging.yml
      vars_files:
      - terraform-yaml/state.yml
      - terraform-secrets/terraform.yml
      - common-staging/staging-pdns.yml
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Successfully deployed pdns on staging
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to deploy dns on staging
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

- name: terraform-powerdns-plan-staging
  plan:
  - aggregate:
    - get: pdns-config
      trigger: true
    - get: pipeline-tasks
  - task: terraform-plan
    file: pipeline-tasks/terraform-apply.yml
    input_mapping:
      terraform-templates: pdns-config
    params: &terraform-staging-params
      TERRAFORM_ACTION: plan
      STACK_NAME: dns-staging
      TEMPLATE_SUBDIR: terraform
      AWS_DEFAULT_REGION: ((aws-region))
      S3_TFSTATE_BUCKET: ((dns-tf-state-bucket))
      TF_VAR_powerdns_server_url: ((powerdns-server-url-staging))
      TF_VAR_powerdns_api_key: ((powerdns-api-key-staging))
  - &notify-slack
    put: slack
    params:
      text_file: terraform-state/message.txt
      text:  |
        :terraform: $BUILD_JOB_NAME needs review
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

- name: terraform-powerdns-apply-staging
  plan:
  - aggregate:
    - get: pdns-config
      passed: [terraform-powerdns-plan-staging]
    - get: pipeline-tasks
  - task: terraform-apply
    file: pipeline-tasks/terraform-apply.yml
    input_mapping:
      terraform-templates: pdns-config
    params:
      <<: *terraform-staging-params
      TERRAFORM_ACTION: apply

- name: smoke-test-staging
  plan:
  - aggregate:
    - get: pdns-config
      passed: [terraform-powerdns-apply-staging]
      trigger: true
  - task: smoke-test-rrsigs
    file: pdns-config/ci/verify-dnssec-rrsig.yml
    params:
      ZONES: sandbox.gov
      ENVIRONMENT: staging
  on_failure:
    put: slack
    params:
      text: |
        :x: Smoke tests failed on staging powerdns
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

- name: plan-pdns-production
  plan:
  - aggregate:
    - get: pdns-config
      passed: [deploy-pdns-staging]
      trigger: true
    - get: pdns-release
      passed: [deploy-pdns-staging]
      trigger: true
    - get: stemcell
      passed: [deploy-pdns-staging]
      trigger: true
    - get: terraform-yaml
      passed: [deploy-pdns-staging]
      trigger: true
    - get: common-production
      trigger: true
  - task: terraform-secrets
    file: pdns-config/ci/terraform-secrets.yml
    params:
      ENVIRONMENT: production
  - put: pdns-deployment-production
    params:
      manifest: pdns-config/deployment.yml
      dry_run: true
      no_redact: true
      stemcells:
      - stemcell/*.tgz
      releases:
      - pdns-release/*.tgz
      ops_files:
      - pdns-config/opsfiles/production.yml
      vars_files:
      - terraform-yaml/state.yml
      - terraform-secrets/terraform.yml
      - common-production/production-pdns.yml
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: PowerDNS production plan is ready for review
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to plan production PowerDNS
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

- name: deploy-pdns-production
  plan:
  - aggregate:
    - get: pdns-config
      passed: [plan-pdns-production]
    - get: pdns-release
      passed: [plan-pdns-production]
    - get: stemcell
      passed: [plan-pdns-production]
    - get: terraform-yaml
      passed: [plan-pdns-production]
    - get: common-production
      passed: [plan-pdns-production]
  - task: terraform-secrets
    file: pdns-config/ci/terraform-secrets.yml
    params:
      ENVIRONMENT: production
  - put: pdns-deployment-production
    params:
      manifest: pdns-config/deployment.yml
      stemcells:
      - stemcell/*.tgz
      releases:
      - pdns-release/*.tgz
      ops_files:
      - pdns-config/opsfiles/production.yml
      vars_files:
      - terraform-yaml/state.yml
      - terraform-secrets/terraform.yml
      - common-production/production-pdns.yml
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Successfully deployed pdns on prodution
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to deploy dns on production
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

- name: smoke-tests-production
  plan:
  - aggregate:
    - get: pdns-config
      passed: [deploy-pdns-production]
      trigger: true
    - get: terraform-yaml
      passed: [deploy-pdns-production]
      trigger: true
    - get: tests-timer
      trigger: true
  - task: smoke-test-rrsigs
    file: pdns-config/ci/verify-dnssec-rrsig.yml
    params:
      ZONES: sandbox.gov
      ENVIRONMENT: production
  - task: smoke-test-ds
    file: pdns-config/ci/verify-dnssec-ds.yml
    params:
      ZONES: sandbox.gov
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Smoke Tests for PowerDNS on prod PASSED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-news-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_failure:
    put: slack
    params:
      text: |
        :x: Smoke Tests for PowerDNS on prod FAILED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
