zone-transfer-ips: (( concat terraform_outputs.public_subnet_az1_cidr ", " terraform_outputs.public_subnet_az2_cidr ))
master-ips: (( join "; " terraform_outputs.staging_dns_private_ips ))
private_named_conf: |
    zone "sandbox.gov" IN {
      type master;
      file "/var/vcap/jobs/pdns/etc/pipe.conf";
      allow-update { none; };
    };

private_pipe_conf: |
    ; designates the start of this zone file in the namespace
    $ORIGIN sandbox.gov.

    ; default expiration time of all resource records without their own TTL value
    $TTL 1h

    ; @ means use $ORIGIN
    @             IN  SOA   ns1.sandbox.gov. cloud-gov-operations.gsa.gov. ( 2018020801 30m 1h 1w 1h )
                            ; primary dns server
                            ; contact email address, replace @ with .
                            ; ( serial # for zone transfers: use YYYYMMDD + 2 digit increment
                            ; refresh every
                            ; retry
                            ; expire
                            ; min TTL )

    @             IN  NS  ns1.sandbox.gov.
    @             IN  NS  ns2.sandbox.gov.

    ; alias record for apex
    @             IN ALIAS dualstack.production-cloudfoundry-main-748290002.us-gov-west-1.elb.amazonaws.com.
    www           IN  CNAME  sandbox.gov.

    *.app.sandbox.gov IN ALIAS dualstack.production-cloudfoundry-apps-1021484088.us-gov-west-1.elb.amazonaws.com.
    ((nameservers))

public_named_conf: |
    zone "sandbox.gov" IN {
      type slave;
      file "/var/vcap/jobs/pdns/etc/sandbox.gov.zone";
      masters {
        ((master-ips));
      };
    };

